function Producto(info, descripcion, nombre, precio, modelo, tipo, numero, id){
	this.info = info;
	this.descripcion = descripcion;
	this.nombre = nombre;
	this.precio = precio;
	this.modelo = modelo;
	this.numero = numero;
	this.tipo = tipo;
	this.id = id;
}

var kimetsu = new Producto("Movie Version Demon Slayer: Kimetsu no Yaiba infinite train ed Visitor Bonus Koyoharu Gotouge purgatory zero Vol", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Kimetsu movie book", 1000, "Especial", "Libro", 1, "kimetsu")
var kimetsu2 = new Producto("ACOS / Demon Slayer: Kimetsu no Yaiba / Parker / Tanjiro Kamado / L Size (Japanese Size)", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Parca Kimetsu no yaiba", 6000, "L", "Ropa", 2, "kimetsu2")
var onePiece = new Producto("Movie Version ONE PIECE STAMPEDE flag cleaner charm collection chopper", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Llavero One piece", 200, "Unico", "Llavero", 3, "onepiece")
var onePiece2 = new Producto("メガハウス POP/ワンピース 【トニートニー・チョッパー/Tonytony.Chopper", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Funko Pop Chopper One Piece", 3000, "Unico", "Funko Pop", 4, "onepiece2")
var kimetsu3 = new Producto("Hasepuro stand mini Acrylic Key Holder Vol.2 Tokitona Ichiro", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Llavero y tsuka para llave Kimetsu", 400, "Unico", "Llavero", 5, "kimetsu3")
var pocky = new Producto("Pocky Biscuit Sticks - Chocolate", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Pocky", 290, "50g", "Comida", 6, "pocky")
var kracie = new Producto("Kracie Popin’ Cookin' Animal Pancake DIY Candy Kit", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Kracie Popin’ Cookin' Animal Pancake", 490, "Unico", "Comida", 7, "kracie")
var kracie2 = new Producto("Kracie Popin' Cookin' Ice Cream Cake Shop DIY Candy Kit", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Kracie Popin' Cookin' Ice Cream Cake ", 460, "Unico", "Comida", 8, "kracie2")
var nezuko = new Producto("Good Smile Company - Nendoroid Nezuko Kamado With Bonus 1194", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Nendoroid Nezuko Kamado", 6000, "Unico", "Nendroid", 9, "nezuko")
var jojo = new Producto("Medicos Super Figure Mascot Strap stone Kamen A Normal version", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "Llavero mascara JoJo", 600, "Unico", "Llavero", 10, "jojo")
var list = [0, kimetsu, kimetsu2, onePiece, onePiece2, kimetsu3, pocky, kracie, kracie2, nezuko, jojo]